version: "3"
services:

  terraria:
    image: jazy5552/terraria-server
    deploy:
      restart_policy:
        delay: 10m
        max_attempts: 10
    labels:
      jazy.terraria-server.description: "Jazys Personal Terraria Server"
      jazy.terraria-server.name: "Jazys Terraria Server"
    networks:
      - terraria
    volumes:
      - "terraria-data:/terraria"

networks:
  terraria:
    external:
      name: "host"

volumes:
  terraria-data:

